### ISSUE TITLE
webpack 2 校对+审校 任务认领说明

### ISSUE THREAD

**Issue by dear-lizhihua** [docschina/webpack.js.org#169]
> 注意：校对时，是以 [git 仓库](https://github.com/webpack-china/webpack.js.org) master 分支的的英文文档为基准做对比，而非 https://webpack.js.org/。

由于现有的文档已经大部分完成翻译，所以下一步准备开始进行文档校对+审校工作。

> [翻译校对及审校之差别](http://fanyi.baike.com/article-27305.html)
> * 校对，其实是对译文的简单检查过程，可通过人工或机器辅助来完成，一般就是看看是否有错译、漏译、标点符号错误、错别字、大小写、拼写错误、单复数、动词时态、数字错误、人名地名错误，等等。这些，具有一般英语基础的人都可以做，有些校对软件可以起到辅助作用。
> * 审校呢，就要比校对高深多了，一般来说，审校人员要比翻译人员水平高，能够发现翻译人员所犯的错误，包括如上所述校对人员应该发现的错误，还有包括文章专业性，译文准确性等等问题，这是一般校对人员以及翻译人员自己都无法或没有能力发现的问题了。

校对+审校暂定计划如下。
#### 人员要求
校对：全员可参与（可以3-5人校对一个文档），主要 1)查找文档中有错译、漏译、标点符号错误、错别字、大小写、拼写错误、单复数等等。2)在准确还原原文意思、不漏翻译词语的前提下，对文档不通顺的地方尽量做到通顺、易于阅读人员去理解。
审校：资深人员参与（官方指定，可以1-2人校对一个文档），从专业的角度，找出不符合官方作者所表明的意思，即校对人员无法发现，只有实际用到的人员才能发现的那些错误。

#### 校对内容
目前情况：
20170212
1)个别章节还是 //todo 待编写完成
2)/content/loaders 和 /content/plugins 由于多数非官方编写，可能会进行一些增删。
3)/content/development 官方可能会新增一些文档。
/content/api（未开始校对）
/content/concepts（未开始校对）
/content/configuration（未开始校对）
/content/development（未开始校对）
/content/guides（计划开始校对）
/content/loaders（未开始校对）
/content/plugins（未开始校对）
/content/pluginsapi（未开始校对）

#### 本次校对迭代20170212
主要对 /content/guides 进行校对+审校，校对完成后线上发布一版。

#### 认领方式
和翻译文档相同，在 [projects](https://github.com/webpack-china/webpack.js.org/projects/1) 的对应 issue 中进行认领。认领格式如下：
1. （全体人员）认领校对：此章节由我校对。
2. （全体人员）校对完成：此章节我已完成校对。
3. （指定人员）认领审校：此章节由我审校。
4. （指定人员）审校完成：此章节我已完成审校。

#### 校对人员规范（暂定）：
关于翻译 - 翻译建议 #20

**Comment by Aladdin-ADD** [comment]
关于校对的流程, 提几个问题大家讨论一下:
+ 校对应该与哪个版本对照, 是与英文官网? 官方仓库? 翻译者PR?(感觉这个最不靠谱,因为提过PR之后, 英文内容有可能已经发生变化)
+ 校对的3~5人应该如何协作?
+ 最终提的PR是应该是到哪个仓库&分支?

**Comment by dear-lizhihua** [comment]
在此说明一下：
## 仓库一共有三个（以下全部简称为英文仓库、中文仓库、我的仓库）：
[英文仓库(webpack/webpack.js.org)](https://github.com/webpack/webpack.js.org)
[中文仓库(webpack-china/webpack.js.org - fork webpack/webpack.js.org)](https://github.com/webpack-china/webpack.js.org)
[我的仓库(yourname/webpack.js.org - fork webpack-china/webpack.js.org)](https://github.com/yourname/webpack.js.org)

### 分支合并方式
##### 「非 /content/loaders」和「非 /content/plugins」
英文仓库 master -> 中文仓库 master
中文仓库 master -> 中文仓库 cn -> 我的仓库 cn
##### 「/content/loaders」和「/content/plugins」
其中「英文仓库 translation」是由 @lcxfs1991 定期拉取更新（手动执行 /scripts/fetch.sh 这个 shell 脚本）
英文仓库 translation -> 中文仓库 translation
中文仓库 translation -> 中文仓库 cn

### 中文站点
[英文站点](https://doc.webpack-china.org/)是由 `npm run build` （官方应该是自动构建到 gh-pages  分支）生成并部署的。
[中文站点](https://doc.webpack-china.org/)是由 `npm run build` （手动构建）生成并部署的。

### 对比差异
通过建立以及合并这些不同的分支，由于 git 基于文件比对差异的强大功能，可以方便的比对每次文件的变更之处。

### 总结
因为「中文仓库 master」可能会滞后于「英文仓库 master」，所以，我们应该以中文仓库 master 分支为基础进行校对。

**Comment by dear-lizhihua** [comment]
补充说明：
以上分支合并方式是直接在中文仓库 cn 分支上做修改，现在是另外一种提交方式：我的仓库提交 pr，中文仓库通过 pr。所以合并方案变更如下：

## 合并方案
分为三个仓库：英文仓库、中文仓库、我的仓库
1. 第一步：英文仓库 master 分支向中文仓库 master 分支合并以及提交(merge & push)。
2. 第二步：中文仓库 master 分支向我的仓库 master 分支合并以及提交(merge & push)。
3. 第三步：我的仓库 master 分支向我的仓库 cn 分支合并以及提交(merge & push)。
4. 第四步：我的仓库 cn 分支向中文仓库 cn 分支提交 pr。
5. 第五步：中文仓库 cn 分支合并(merge) 我的仓库 cn 分支的 pr。
