### ISSUE TITLE
webpack翻译人员收集

### ISSUE THREAD

**Issue by lcxfs1991** [docschina/webpack.js.org#180]
示例：
github: https://github.com/lcxfs1991
nickname: lcxfs1991

**Comment by scq000** [comment]
github: http://github.com/scq000
nickname: scq000
avator: 
![](https://avatars2.githubusercontent.com/u/12999391?v=3&s=460)

**Comment by tao1991123** [comment]
github:  github.com/tao1991123
nickname: muchen
avator:
![touxiang](http://7xqq2h.com1.z0.glb.clouddn.com/image/png/touxiang.png)

**Comment by shisaq** [comment]
github: [https://github.com/shisaq](https://github.com/shisaq)
nickname: shisaq
avator: 
![](https://raw.githubusercontent.com/shisaq/images/master/images/avator.jpg)

**Comment by superpig** [comment]
github: https://github.com/superpig
nickname: superpig
avator:
![wechatimg3](https://cloud.githubusercontent.com/assets/5066518/23161423/09ae5f2a-f865-11e6-868d-5ba736efeb95.jpeg)

**Comment by lgh06** [comment]
>I just pushed one fix till now...
May me be added to the contributor list...?
I think this can encourage me to do more and be proactive.
Maybe I am not a well-known contributor of open-source, 
I am confident with my English,I can translate without the help of Google Translator or sth else.



github: https://github.com/lgh06
nickname: HapLeo
avator: 
![image](https://cloud.githubusercontent.com/assets/1688639/23346521/d795475e-fcd5-11e6-974a-e01e5548d689.png)

**Comment by lcxfs1991** [comment]
漏掉的我中午补充一下。

**Comment by dear-lizhihua** [comment]
这个issue加在readme.md最下面吧，好让后面翻译的同学看到，然后进来留一下名字。

**Comment by dear-lizhihua** [comment]
好了，加进去了。

**Comment by hijiangtao** [comment]
github: https://github.com/hijiangtao
nickname: hijiangtao
avator:

**Comment by dear-lizhihua** [comment]
@hijiangtao https://github.com/dear-lizhihua/webpack.js.org/commit/585b12fcca92a67bfb8eb0aed5080298f87cd538
已加入，下次提 pr 合并

**Comment by fa93hws** [comment]
https://github.com/fa93hws
nickname: fa93hws

**Comment by dear-lizhihua** [comment]
OK，已加入，下次我提交 pr 就能看到

**Comment by guyunxiang** [comment]
github: https://github.com/guyunxiang
nickname: guyunxiang

**Comment by dear-lizhihua** [comment]
@guyunxiang 已加入，下次我提交 pr 就能看到

**Comment by lukastong** [comment]
github: https://github.com/lukastong
nickname: lukastong

**Comment by lukastong** [comment]
@dear-lizhihua 
github: https://github.com/lukastong
nickname: lukastong

**Comment by dear-lizhihua** [comment]
https://github.com/webpack-china/webpack.js.org/pull/377/commits/57fb4d42681f6d3391cb3eee883f7b70553dc9b9

@AlenQi @lukastong @QC-L @SimonLeeee
近期提交 pr 的贡献者都加进去了

**Comment by Victor716** [comment]
github: https://github.com/Victor716
nickname: Victor

**Comment by dear-lizhihua** [comment]
@Victor716 没找到你的提交记录，git 配置是 Victor 这个名字吗？

**Comment by Cleam** [comment]
github: https://github.com/cleam
nickname: cleam

**Comment by xianghui-ma** [comment]
github: https://github.com/xianghui-ma
nickname: small_ma
avator:

**Comment by zzyxka** [comment]
github: https://github.com/zzyxka
nickname: zhangzeyi

**Comment by xiaoqiuer** [comment]
https://github.com/xiaoqiuer

**Comment by xiaoqiuer** [comment]
github: https://github.com/xiaoqiuer
nickname: xiaoqiuer

**Comment by mercurywang** [comment]
github: https://github.com/mercurywang
nickname: mercurywang

**Comment by 92hackers** [comment]
github: [https://github.com/92hackers](https://github.com/92hackers)
nickname: 92hackers

**Comment by gauliang** [comment]
github: https://github.com/gauliang
nickname: gauliang

**Comment by fine405** [comment]
github: https://github.com/fine-bot
nickname: fine-bot

**Comment by KimYangOfCat** [comment]
github: https://github.com/KimYangOfCat
nickname: KimYang

**Comment by Usualminds** [comment]
github: https://github.com/Usualminds
nickname: Usualminds

**Comment by fikyair** [comment]
github: https://github.com/fikyair
nickname: fikyair

**Comment by a847244052** [comment]
github: https://github.com/a847244052
nickname: a847244052
