### ISSUE TITLE
关于翻译/校对 - 任务认领

### ISSUE THREAD

**Issue by dear-lizhihua** [docschina/webpack.js.org#19]
### [webpack 2 翻译任务认领说明 - 入口目录](https://github.com/webpack-china/webpack.js.org/issues/17)

@all，注意
1. TODO 是 webpack 官方尚未编写完整，暂时不用翻译
2. 极其简短的文档不计在完成进度中（因为有可能是官方还没有详细编写）。避免 merge 官方分支后，出现未翻译却记录已翻译的情况。
3. 翻译时间建议不超过 2 周 14 天时间，过期后可由其他人重新认领。
4. 翻译彻底完成后，webpack-china 官方维护人员关闭对应 issue。

> 「webpack 中文」官方网址：[点击访问https](https://doc.webpack-china.org) [点击访问http](http://doc.webpack-china.org)
> 「webpack 中文」QQ 群： `425986482`

### 加入微信群
为了加速 webpack 的推广，我们决定建立一个 webpack 中文翻译的微信群，大家在里面可以互相交流。
大家先添加我的微信号 wuwangbufu002，加的时候报下你的 github 名称，我将加你好友，然后拉入微信群。

### 认领说明

翻译
- 翻译前，请在[此处认领](https://github.com/webpack-china/webpack.js.org/projects/1)

- 认领示例：[/content/guides/index.md - 我是认领示例哦](https://github.com/webpack-china/webpack.js.org/issues/21)

- 认领格式 ：此章节由我翻译，翻译时间为 2017.01.01-2017.01.14。

- 如果本人认领，然后发现没有时间翻译，可以取消认领

- 取消认领格式：此章节我暂时没有时间翻译，请其他同学协助代为翻译，谢谢！

- 翻译完成，到领取的 issue 中回复：此章节我已翻译完成 #453（记得把 pr 编号带上，#号+数字编号会自动关联相应的 pr）。官方维护人员收到留言消息提示后，修改对应 issue 的状态。

**Comment by LeoEatle** [comment]
请问校对工作如何进行呢？

**Comment by dear-lizhihua** [comment]
@LeoEatle 
看这篇介绍，[webpack 2 校对+审校 任务认领说明](https://github.com/webpack-china/webpack.js.org/issues/169)，主要是在 [projects](https://github.com/webpack-china/webpack.js.org/projects/1) 认领。
