### ISSUE TITLE
关于翻译 - 翻译建议

### ISSUE THREAD

**Issue by dear-lizhihua** [docschina/webpack.js.org#20]
### 参与：
- 如果你看到错别字、漏译、错译，请直接提交 pr （[帮助](https://help.github.com/articles/using-pull-requests/)）。
- 如果你看到网站问题，或者创建一个 issue，或者直接提交 pr。
- 如果你对已有翻译有异议，建议创建一个 issue 讨论。
- 如果你想修改英文内容，请去 [webpack.js.org 官方][webpack.js.org]提交 pr。
- 如果你想求教 webpack 使用问题，请去[webpack 中文论坛][forum]。
- 如果你遇到 webpack 的问题，请去 [webpack 项目][webpack]，
- 创建 issue 并提供演示。可以在 JSBin, JSFiddle, Codepen 等网站创建演示。
- 由于本人也不是完全精通 webpack，以下术语如有理解错误的地方，请在此 issue 下方讨论，或联系本人，讨论完成后修改。

### 翻译要求
- 保持一致，清晰
- 英文与中文的行数请保持一致！！！
- 汉字，字母，数字等之间以一个空格隔开（以英文单词开头/结尾时，和前面/后面的中文符号不需要空格）。
- 中文使用中文符号，英文使用英文符号。
- 专有词注意大小写，如 webpack（小写不要写错），HTML，CSS，JavaScript。
- 术语与已有译文保持一致，如果有异议请先在 issue 中讨论。
- 专有名词为便于查阅者理解，建议后跟「英文括号加词组」解释说明，如：...模块热替换(Hot Module Replacement)...（中文后面的英文注释，用英文括号扩起来，中文括号太占地方，看起来不够协调和美观）
- 代码只翻译注释。
- 校对后对应修改提交 pull-request，静待官方人员 merge。

### 翻译词汇
[翻译词汇](https://github.com/docschina/translator-guide/blob/master/%E7%BF%BB%E8%AF%91%E8%AF%8D%E6%B1%87.md)

**Comment by hijiangtao** [comment]
compiler 不建议直接翻译, 是否 compilation 也加入相同规则? 我在查看概念系列章节时发现多次出现的 compilation (直译应为编译过程) 也未被翻译成中文?

**Comment by dear-lizhihua** [comment]
1. compilation 如果指的是 webpack 中的 JavaScript 对象，就不做翻译；如果是指编译过程，那就需要翻译。compiler、parser 等同理。
2. 考虑到 webpack 文档中存在大量提到 library 的地方，为了特殊标明这个概念，所以对 library 不做强行翻译。毕竟 webpack 中有几种库，比如 library、vendor、external，但是含义有一些细微的差别。
如果我们的文档统一用 library，大家也逐步接受 library，以后就会更加明确指的是遵循 UMD 等模块规范的 library。

**Comment by Otto-J** [comment]
最后词汇翻译的链接，时间太久了已经没了，需要更新
