### ISSUE TITLE
文档发现一处错误

### ISSUE THREAD

**Issue by MXXXXXS** [docschina/webpack.js.org#539]
[https://webpack.docschina.org/guides/development/](url)

> 现在，webpack 观察文件的同时，我们先移除我们之前引入的错误：

>src/print.js
>export default function printMe() {
>\-  cosnole.log('I get called from print.js!');
>\+  console.log('I get called from print.js!');
>  }

>现在,保存文件并检查终端窗口。应该可以看到 webpack 自动重新编译修改后的模块！

上文代码中, 第一个`console.log`应改为`console.error`

**Comment by TheNorthWindRises** [comment]
我也看到了，但你仔细往下看，这里就是为了演示错误而写的错误代码

**Comment by MXXXXXS** [comment]
> 我也看到了，但你仔细往下看，这里就是为了演示错误而写的错误代码

不, 我指的就是下面的那个(恢复之前的故意写错的代码). 这里两个都是`console.log`了, 删掉的那个应该是`console.error`
