### ISSUE TITLE
管理依赖有处错误

### ISSUE THREAD

**Issue by newBird01** [docschina/webpack.js.org#602]
https://webpack.docschina.org//guides/dependency-management
![image](https://user-images.githubusercontent.com/25924193/58447598-77868600-8137-11e9-80d1-5573ef4a5e40.png)

**Comment by newBird01** [comment]
![image](https://user-images.githubusercontent.com/25924193/58447633-984edb80-8137-11e9-8011-8d347c154e6e.png)

**Comment by dear-lizhihua** [comment]
https://webpack.docschina.org/glossary#r
