### ISSUE TITLE
清除dist文件夹文档中引入的clean-webpack-plugin插件新版本引入方式已变更

### ISSUE THREAD

**Issue by StrayCatAN** [docschina/webpack.js.org#618]
- [ ] Check the current issues to ensure you aren't creating a duplicate.
- [ ] Consider making small typo fixes and such directly as pull requests.
- [ ] For the voting application, go to https://github.com/webpack-contrib/voting-app.
- [ ] For loader/plugin docs, consider opening an issue in the corresponding repository.
- [ ] No existing issue? Go ahead and open a new one.
- __Remove these instructions from your PR as they are for your eyes only.__

https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional相关变更地址

错误：
`+ const CleanWebpackPlugin = require('clean-webpack-plugin');`

正确：
`+ const {CleanWebpackPlugin} = require('clean-webpack-plugin');`

**Comment by qizhou23** [comment]
现在[官方文档](url:https://www.npmjs.com/package/clean-webpack-plugin)也使用的是新的写法了，如果依旧使用旧的写法会报错：
```
TypeError: CleanWebpackPlugin is not a constructor
```

**Comment by zanllp** [comment]
刚pr了这个，点过来就看到了

**Comment by xiami99** [comment]
我也刚发现这个问题，new CleanWebpackPlugin(['dist']), 这句的参数语法也是错误的，应该使用new CleanWebpackPlugin({xxx:['dist]}); 或者new CleanWebpackPlugin()

**Comment by guoguo520** [comment]
错误用法：
const CleanWebpackPlugin = require('clean-webpack-plugin');

正确用法：
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

错误用法：
plugins: [
        new CleanWebpackPlugin(['dist])
]

正确用法：
plugins: [
        new CleanWebpackPlugin()
]

**Comment by YunYouJun** [comment]
GitHub 上[文档](https://github.com/docschina/webpack.js.org/blob/cn/src/content/guides/output-management.md#%E6%B8%85%E7%90%86-dist-%E6%96%87%E4%BB%B6%E5%A4%B9)看起来已经变更，但中文官网[文档](https://webpack.docschina.org/guides/output-management/#%E6%B8%85%E7%90%86-dist-%E6%96%87%E4%BB%B6%E5%A4%B9)仍旧未更新。

**Comment by QC-L** [comment]
不好意思，来迟了，已合并修复
