### ISSUE TITLE
webapck4.x中插件CleanWebpackPlugin的引用

### ISSUE THREAD

**Issue by Jean1988** [docschina/webpack.js.org#664]
由之前const  CleanWebpackPlugin = require('clean-webpack-plugin') 改为 const { CleanWebpackPlugin } = require('clean-webpack-plugin')，不然run build的时候会报TypeError: CleanWebpackPlugin is not a constructor

**Comment by Palenew** [comment]
项目中是对的，但是中文站里面没有更新。
有趣
